Fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -62,6 +62,19 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
+
+      - name: Prepare EC2 deploy folder
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          port: 22
+          script: |
+            mkdir -p /home/ubuntu/src/database
+            rm -f /home/ubuntu/docker-compose.yml
+            rm -f /home/ubuntu/src/database/schema.sql
+
       - name: Copy docker-compose.yml to EC2
         uses: appleboy/scp-action@v0.1.7
         with:
@@ -71,6 +84,8 @@ jobs:
           port: 22
           source: "docker-compose.yml,src/database/schema.sql"
           target: "/home/ubuntu/"
+          overwrite: true
+
       - name: Deploy to Staging
         uses: appleboy/ssh-action@v1.0.3
         env:
@@ -85,27 +100,33 @@ jobs:
           envs: DB_PASSWORD,DOCKER_USERNAME,DOCKER_PASSWORD
           script: |
             cd /home/ubuntu
+
             echo "1. Creating .env file with database credentials and image tag..."
             echo "DB_HOST=db" > .env
             echo "DB_USER=root" >> .env
             echo "DB_PASS=${DB_PASSWORD}" >> .env
             echo "DB_NAME=login_api_demo" >> .env
-            echo "IMAGE_TAG=${{github.sha}}" >> .env
-            echo "DOCKER_USERNAME=${DOCKER_USERNAME}" >> .env 
+            echo "IMAGE_TAG=${{ github.sha }}" >> .env
+            echo "DOCKER_USERNAME=${DOCKER_USERNAME}" >> .env
+
             echo "2. Logging in and pulling the latest image..."
-            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
-            docker-compose pull
-            docker-compose up -d 
+            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
+
+            docker compose pull
+            docker compose up -d
+
             echo "3. Running smoke tests..."
             sleep 15
+
             if curl -s -f http://localhost > /dev/null; then
-            echo "Smoke test passed!"
-            else  
-            echo "Smoke test failed!"
-            sed -i "s/IMAGE_TAG=.*/IMAGE_TAG=${{ github.event.before }}/g" .env
-            docker-compose pull
-            docker-compose up -d
-            echo "Rolled back to previous image."
-            exit 1
+              echo "Smoke test passed!"
+            else
+              echo "Smoke test failed!"
+              sed -i "s/IMAGE_TAG=.*/IMAGE_TAG=${{ github.event.before }}/g" .env
+              docker compose pull
+              docker compose up -d
+              echo "Rolled back to previous image."
+              exit 1
             fi
+
             docker image prune -f
